# Generated by Django 6.0 on 2026-01-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': '01. Планы',
                'ordering': ['-datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerateTokenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Токен')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Активирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='plans.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Токен плана',
                'verbose_name_plural': '02. Токены планов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('approved', 'Принято'), ('rejected', 'Отклонено'), ('removed_into_chat_group', 'Удален из группы чата')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_users', to='plans.plan', verbose_name='План')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_users', to='plans.generatetokenplan', verbose_name='Токен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник плана',
                'verbose_name_plural': '03. Участники планов',
                'ordering': ['-created_at'],
                'unique_together': {('plan', 'user', 'token')},
            },
        ),
    ]
