# Generated manually to create missing tables

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency('accounts.CustomUser'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create plans_generatetokenplan table if not exists
            CREATE TABLE IF NOT EXISTS "plans_generatetokenplan" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "token" varchar(255) NOT NULL UNIQUE,
                "is_activated" boolean NOT NULL DEFAULT false,
                "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "plan_id" bigint NOT NULL
            );
            
            -- Create indexes if not exists
            CREATE INDEX IF NOT EXISTS "plans_generatetokenplan_token_fb00d41c_like" ON "plans_generatetokenplan" ("token" varchar_pattern_ops);
            CREATE INDEX IF NOT EXISTS "plans_generatetokenplan_plan_id_20be1524" ON "plans_generatetokenplan" ("plan_id");
            
            -- Add foreign key constraint if not exists
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'plans_generatetokenplan_plan_id_20be1524_fk_plans_plan_id'
                ) THEN
                    ALTER TABLE "plans_generatetokenplan" 
                    ADD CONSTRAINT "plans_generatetokenplan_plan_id_20be1524_fk_plans_plan_id" 
                    FOREIGN KEY ("plan_id") REFERENCES "plans_plan" ("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            
            -- Create plans_planuser table if not exists
            CREATE TABLE IF NOT EXISTS "plans_planuser" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "status" varchar(50) NOT NULL DEFAULT 'pending',
                "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "plan_id" bigint NOT NULL,
                "token_id" bigint NOT NULL,
                "user_id" bigint NOT NULL
            );
            
            -- Create indexes if not exists
            CREATE INDEX IF NOT EXISTS "plans_planuser_plan_id_b5ee0664" ON "plans_planuser" ("plan_id");
            CREATE INDEX IF NOT EXISTS "plans_planuser_token_id_795d3769" ON "plans_planuser" ("token_id");
            CREATE INDEX IF NOT EXISTS "plans_planuser_user_id_4b05a8d8" ON "plans_planuser" ("user_id");
            
            -- Add unique constraint if not exists
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'plans_planuser_plan_id_user_id_token_id_60bc7005_uniq'
                ) THEN
                    ALTER TABLE "plans_planuser" 
                    ADD CONSTRAINT "plans_planuser_plan_id_user_id_token_id_60bc7005_uniq" 
                    UNIQUE ("plan_id", "user_id", "token_id");
                END IF;
            END $$;
            
            -- Add foreign key constraints if not exists
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'plans_planuser_plan_id_b5ee0664_fk_plans_plan_id'
                ) THEN
                    ALTER TABLE "plans_planuser" 
                    ADD CONSTRAINT "plans_planuser_plan_id_b5ee0664_fk_plans_plan_id" 
                    FOREIGN KEY ("plan_id") REFERENCES "plans_plan" ("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'plans_planuser_token_id_795d3769_fk_plans_generatetokenplan_id'
                ) THEN
                    ALTER TABLE "plans_planuser" 
                    ADD CONSTRAINT "plans_planuser_token_id_795d3769_fk_plans_generatetokenplan_id" 
                    FOREIGN KEY ("token_id") REFERENCES "plans_generatetokenplan" ("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'plans_planuser_user_id_4b05a8d8_fk_accounts_customuser_id'
                ) THEN
                    ALTER TABLE "plans_planuser" 
                    ADD CONSTRAINT "plans_planuser_user_id_4b05a8d8_fk_accounts_customuser_id" 
                    FOREIGN KEY ("user_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "plans_planuser";
            DROP TABLE IF EXISTS "plans_generatetokenplan";
            """
        ),
    ]
