# Generated by Django 5.2.6 on 2026-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_create_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user_plan_number',
            field=models.IntegerField(default=1, verbose_name='Номер плана пользователя'),
        ),
        migrations.AlterField(
            model_name='generatetokenplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
