# Generated by Django 5.2.6 on 2026-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_planuser_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planuser',
            name='token',
        ),
        migrations.AlterModelOptions(
            name='planuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Участник плана', 'verbose_name_plural': '02. Участники планов'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='GenerateTokenPlan',
        ),
    ]
