# Generated by Django 5.2.6 on 2026-01-24 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_planuser_token_alter_planuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateTokenPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Максимальное количество использований')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Текущее количество использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Создатель токена')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='plans.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Токен приглашения',
                'verbose_name_plural': '03. Токены приглашений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='plans_gener_token_ec9311_idx'), models.Index(fields=['plan', 'is_active'], name='plans_gener_plan_id_ecd82d_idx')],
            },
        ),
    ]
